# Generated by Django 3.1.4 on 2021-01-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_type', models.TextField()),
                ('name', models.TextField()),
                ('range_of_applicants', models.TextField()),
                ('grounds_for_suspending_the_provision_of_the_service', models.TextField()),
                ('list_of_documents_required_to_provide_the_service', models.TextField()),
                ('reasons_for_refusing_to_accept_documents', models.TextField()),
                ('result_of_providing_the_service', models.TextField()),
                ('url_order', models.TextField()),
                ('order_name', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name_plural': 'People'},
        ),
    ]
