# Generated by Django 3.1.4 on 2021-01-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='name',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='window',
            name='name1',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
