# Generated by Django 3.1.4 on 2021-01-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210105_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='window',
            name='name1',
        ),
    ]
