# Generated by Django 3.1.4 on 2021-01-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_equeue'),
    ]

    operations = [
        migrations.AddField(
            model_name='equeue',
            name='name',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
