# Generated by Django 3.1.4 on 2021-01-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210107_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requeststatus'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
