# Generated by Django 3.1.4 on 2021-01-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210107_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('STATUS_1', 'STATUS_1'), ('STATUS_2', 'STATUS_2'), ('STATUS_3', 'STATUS_3')], default='STATUS_1', max_length=30),
        ),
    ]
